name: streamlit-prophet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit
      - prophet
      - pandas
      - matplotlib
      - seaborn
      - scikit-learn
      - ipykernel